Sales Process/SalesProcess.WEB/Controllers/BuyerController.cs
using SalesProcess.Core.Entities;
using SalesProcess.Core.IServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesProcess.WEB.Controllers
{
    public class BuyerController : Controller
    {
        private IBuyersService _buyerService;
        public BuyerController(IBuyersService _buyerService)
        {
            this._buyerService = _buyerService;
        }
        // GET: Buyer
        public ActionResult BuyersList()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetBuyer(long id)
        {
            return Json(_buyerService.GetBuyer(id), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetAllBuyers(bool? pIsActive)
        {
            var buyers = _buyerService.GetAllBuyers(pIsActive);

            return Json(buyers, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddBuyer(Buyers buyer)
        {
            buyer = _buyerService.AddBuyer(buyer);
            return Json(buyer, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateBuyer(Buyers buyer)
        {
            _buyerService.UpdateBuyer(buyer);
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteBuyer(long id)
        {
            _buyerService.DeleteBuyer(id);
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult BuyersOfNewOrder(long[] pSelectedBuyers)
        {
            var buyers = _buyerService.GetAllBuyers(true).Where(x=> pSelectedBuyers.Contains(x.Id)).ToList();

            return Json(buyers, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult BuyersOrderedByOrder(long pId)
        {
            var records = _buyerService.GetBuyersOrderedByOrder(pId);
            return Json(records, JsonRequestBehavior.AllowGet);
        }
    }
}

Sales Process/SalesProcess.WEB/Controllers/OrderController.cs
using SalesProcess.Core.IServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesProcess.WEB.Controllers
{
    public class OrderController : Controller
    {
        private IOrdersService _orderService;
        public OrderController(IOrdersService _orderService)
        {
            this._orderService = _orderService;
        }
        // GET: Order
        public ActionResult Order()
        {
            return View();
        }

        public ActionResult Payment()
        {
            return View();
        }
        public ActionResult NewOrder()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetAllOrders(bool? pIsPaid)
        {
            var result = _orderService.GetAllOrders(pIsPaid);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetBuyersOfOrder(long id)
        {
            var result = _orderService.GetBuyersByOrder(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetOrdersByBuyer(long buyerId)
        {
            var result = _orderService.GetOrdersByBuyer(buyerId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult PlaceOrder(long[] pProductIds, int[] pProductQuantity, long[] pBuyerIds, double[] pBuyersPCT, decimal pTotalPrice)
        {
            _orderService.PlaceOrder(pProductIds, pProductQuantity, pBuyerIds, pBuyersPCT, pTotalPrice);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult MakePayment(long pId, long[] pBuyerOrderIds, decimal[] pBuyersPayments)
        {
            _orderService.MakePayment(pId, pBuyerOrderIds, pBuyersPayments);
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetPaymentLogOfBuyer(long pBuyerId, long pOrderId)
        {
            var records = _orderService.GetPaymentLogByBuyers(pBuyerId, pOrderId);
            return Json(records, JsonRequestBehavior.AllowGet);
        }
    }
}

Sales Process/SalesProcess.WEB/Controllers/ProductController.cs
using SalesProcess.Core.Entities;
using SalesProcess.Core.IServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesProcess.WEB.Controllers
{
    public class ProductController : Controller
    {
        private IProductsService _productService;
        public ProductController(IProductsService _productService)
        {
            this._productService = _productService;
        }

        public ActionResult Products()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetAllProducts(bool? pIsAvailable)
        {
            var products = _productService.GetAllProducts(pIsAvailable).OrderByDescending(x => x.Id);

            return Json(products, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddProduct(Products product)
        {
            _productService.AddProduct(product);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateProduct(Products product)
        {
            _productService.UpdateProduct(product);
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteProduct(long id)
        {
            _productService.DeleteProduct(id);
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ProductsOfNewOrder(long[] pSelectedProducts)
        {
            var products = _productService.GetAllProducts(true).Where(x => pSelectedProducts.Contains(x.Id)).ToList();
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ProductsOrderedByOrder(long pId)
        {
            var records = _productService.GetProductsOrderedByOrder(pId);
            return Json(records, JsonRequestBehavior.AllowGet);
        }
    }
}

Sales Process/SalesProcess.WEB/Views/Buyer/BuyersList.cshtml
@{
    ViewBag.Title = "Buyers";
}
<script type="text/javascript" src="@Url.Content("~/Scripts/App/buyers.js")"></script>

<div class="card-material">
    <div class="buyers-head row">
        <div class="col-sm-4 col-md-4">
            <h5 class="page-title">Buyers</h5>
        </div>
        <div class="col-sm-8 col-md-8 text-right">
            <button type="button"
                    class="btn btn-outline-info custom-grid-btn"
                    data-toggle="modal"
                    data-target="#BuyersModal"
                    onclick="AddBuyerModal(event)">
                <i class="fas fa-plus-circle"></i> Create New Buyer
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-cyan">
                <tr>
                    <th class="cell-min">Buyer Name</th>
                    <th class="cell-min text-center">Buyer Code</th>
                    <th class="cell-min text-center">Buyer Region</th>
                    <th class="cell-min text-center">Buyer Mobile</th>
                    <th class="cell-min text-center">Buyer Email</th>
                    <th class="text-center cell-min">Action</th>
                </tr>
            </thead>
            <tbody class="buyers-list"></tbody>
        </table>
    </div>
</div>

<div class="card-material" id="BuyersPaymentDetails" style="display:none;">
    <div class="row">
        <div class="col-md-12">
            <a href="javascript:void(0)" class="page-close" onclick="ClosePaymentDetails()">&times;</a>
        </div>
    </div>
    <input type="hidden" id="BuyersId" />
    <h5 class="page-title text-center">Payemnts of <b class="buyers-name"></b></h5>
    <div class="form-group row">
        <label for="Payment" class="col-sm-1 col-form-label">Order</label>
        <div class="col-sm-4">
            <select class="selectpicker" id="ddlOrdersPayment" data-live-search="true" onchange="LoadPaymentLog()"></select>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-cyan">
                <tr>
                    <th class="cell-min">Order ID</th>
                    <th class="text-center cell-min">Paid ON</th>
                    <th class="text-center cell-min">Paid Amount</th>
                    <th class="text-center cell-min">Total Bill</th>
                </tr>
            </thead>
            <tbody id="PaymentLog"></tbody>
        </table>
    </div>
</div>
@Html.Partial("_BuyerModalWindow")

Sales Process/SalesProcess.WEB/Views/Buyer/_BuyerModalWindow.cshtml
@* Modal Screen *@
<div class="modal fade" id="BuyersModal" tabindex="-1" role="dialog" aria-labelledby="BuyersModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="BuyersModalTitle">New Buyer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="BuyersId" />
                    <div class="form-group row">
                        <label for="buyersName" class="col-sm-4 col-form-label">Name</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="BuyersName" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="buyersCode" class="col-sm-4 col-form-label">Code</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="BuyersCode" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="buyersCode" class="col-sm-4 col-form-label">Region</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="BuyersRegion" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="buyersMobile" class="col-sm-4 col-form-label">Mobile</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="BuyersMobile" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="buyersEmail" class="col-sm-4 col-form-label">Email</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="BuyersEmail" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success" id="AddUser" onclick="AddBuyer(event)">Save</button>
                <button type="button" class="btn btn-primary" id="UpdateUser" onclick="EditBuyer(event)">Update</button>
            </div>
        </div>
    </div>
</div>

Sales Process/SalesProcess.WEB/Views/Order/NewOrder.cshtml
@{
    ViewBag.Title = "Place Order";
}

<style>
    .bootstrap-select button {
        border: 1px solid rgba(0,0,0,0.2) !important;
    }

    .dropdown.bootstrap-select.show-tick {
        width: 100% !important;
    }

    .dropdown-menu {
        min-width: 220px !important;
        width: 100% !important;
    }

    .order-selection-final {
        display: flex;
        align-content: center;
        justify-content: center;
    }

    .order-details {
        display: none;
    }
</style>
<script type="text/javascript" src="@Url.Content("~/Scripts/App/place-order.js")"></script>

<div class="card-material">
    <h5 class="page-title text-center">Place your order</h5>
    <hr />
    <div class="form-group row">
        <label for="Products" class="col-sm-2 col-form-label">Select Products:</label>
        <div class="col-sm-10">
            <select class="selectpicker" id="ddlProducts" multiple data-live-search="true"></select>
        </div>
    </div>
    <div class="form-group row">
        <label for="Buyers" class="col-sm-2 col-form-label">Select Buyers</label>
        <div class="col-sm-10">
            <select class="selectpicker" id="ddlBuyers" multiple data-live-search="true"></select>
        </div>
    </div>
    <div class="order-selection-final">
        <button class="btn btn-info" type="button" onclick="ProceedToNext()">Continue</button>
    </div>
</div>
<div id="OrderDetails">
    <div class="card-material order-details">
        <h5 class="text-center page-title">Order Summary</h5>
        <h5><strong>Products</strong></h5>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Sl.</th>
                        <th class="cell-min">Name</th>
                        <th class="text-center cell-min">Code</th>
                        <th class="text-center cell-min">Available Qty.</th>
                        <th class="text-center cell-min">Price (Per Pcs) BDT</th>
                        <th class="text-center cell-min">Order Qty</th>
                        <th class="text-center cell-min">Total Price (BDT)</th>
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <tbody id="tblProducts"></tbody>
            </table>
        </div>
        <div class="total-order row">
            <div class="col-md-4 offset-md-8">
                <span>Order Total Amount:&emsp;<b id="GrandTotal">0</b>/=</span>
            </div>
        </div>
        <hr />
        <h5><strong>Buyers</strong></h5>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Sl.</th>
                        <th class="cell-min">Name</th>
                        <th>Code</th>
                        <th class="text-center cell-min">Region</th>
                        <th class="text-center cell-min">Payable (%)</th>
                        <th class="text-center cell-min">Payable Amount</th>
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <tbody id="tblBuyers"></tbody>
            </table>
        </div>
        <div class="order-selection-final mt-3">
            <button type="button"
                    class="btn btn-info"
                    @*data-toggle="modal"
                data-target="#ConfirmOrderModal"*@
                    onclick="ConfirmOrderModal(event)">
                Checkout
            </button>
        </div>
    </div>
</div>
@Html.Partial("_ConfirmOrderModal")

Sales Process/SalesProcess.WEB/Views/Order/Order.cshtml
@{
    ViewBag.Title = "Orders";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/App/orders.js")"></script>

<div class="card-material">
    <div class="buyers-head row">
        <div class="col-sm-4 col-md-4">
            <h5 class="page-title">Orders</h5>
        </div>
        <div class="col-sm-8 col-md-8 text-right">
            <a href="@Url.Action("NewOrder", "Order")" class="btn btn-outline-info custom-grid-btn"><i class="fas fa-plus-circle"></i> Make an Order</a>
        </div>
    </div>


    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-cyan">
                <tr>
                    <th class="cell-min">Order ID</th>
                    <th class="text-center cell-min">Date</th>
                    <th class="text-center cell-min">Total</th>
                    <th class="text-center cell-min">Status</th>
                    <th class="text-center cell-min">Actions</th>
                </tr>
            </thead>
            <tbody class="orders-list"></tbody>
        </table>
    </div>
</div>
@Html.Partial("_InvoiceModal")

Sales Process/SalesProcess.WEB/Views/Order/Payment.cshtml
@{
    ViewBag.Title = "Payment";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/App/payment.js")"></script>

<div class="card-material">
    <h5 class="page-title text-center">Payments</h5>
    <hr />
    <div class="form-group row">
        <label for="Payment" class="col-sm-1 col-form-label font-weight-bold">Orders</label>
        <div class="col-sm-5">
            <select class="selectpicker" id="ddlOrders" data-live-search="true" onchange="ChangeOrder()"></select>
        </div>
    </div>
    <hr />
    <div id="payment-entry" style="display:none">
        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Buyer Name</th>
                        <th class="text-center width-20">Total</th>
                        <th class="text-center width-20">Paid</th>
                        <th class="text-center width-20">Due</th>
                        <th class="text-center width-20">Payment</th>
                    </tr>
                </thead>
                <tbody id="tblPayment"></tbody>
            </table>
        </div>
        <div class="text-right">
            <button class="btn btn-info" onclick="MakePayment(event)"><i class="fas fa-save"></i>&ensp;Save</button>
        </div>
    </div>
</div>

Sales Process/SalesProcess.WEB/Views/Order/_ConfirmOrderModal.cshtml
@* Modal Screen *@
<div class="modal fade" id="ConfirmOrderModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmOrderModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="position:absolute; right:5px;z-index:2;">
                <span aria-hidden="true">&times;</span>
            </button>
            <div class="modal-body">
                <h3 class="text-center page-title">Sales Process System</h3>
                <p class="text-center subtitle">Gulshan 1,Navana Tower (7th floor) 45, <br />Gulshan South C/A,Circle 1,<br />Dhaka, Bangladesh</p>
                <p class="text-right" style="font-size:12px;"><strong>Date: </strong><b id="today"></b></p>
                <h5 class="text-center page-title">Order Summary</h5>
                <hr />
                <h6 class="text-center subtitle"><strong>Products</strong></h6>
                <div class="table-responsive">
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr>
                                <th style="width:5%;">Sl.</th>
                                <th>Name</th>
                                <th style="width:20%;" class="text-center">Quantity</th>
                                <th style="width:20%;" class="text-center">Price</th>
                            </tr>
                        </thead>
                        <tbody id="orderScreenProducts"></tbody>
                    </table>
                </div>
                <br />
                <h6 class="text-center subtitle"><strong>Buyers</strong></h6>
                <div class="table-responsive">
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr>
                                <th style="width:5%;">Sl.</th>
                                <th>Name</th>
                                <th style="width:20%;" class="text-center">Amount</th>
                            </tr>
                        </thead>
                        <tbody id="orderScreenBuyers"></tbody>
                    </table>
                </div>
                <div class="nb">
                    <strong style="font-size:12px;">** Confirm your payment in order to get your products</strong><br />
                    <strong style="font-size:12px;">** Vat and taxes are included</strong>
                </div>
            </div>
            
            <div class="modal-footer" style="justify-content:center;">
                <button class="btn btn-success" type="button" onclick="Confirmation(event)" id="ConfirmOrder">Confirm Order</button>
            </div>
        </div>
    </div>
</div>

Sales Process/SalesProcess.WEB/Views/Order/_InvoiceModal.cshtml
@* Modal Screen *@
<div class="modal fade" id="InvoiceModal" tabindex="-1" role="dialog" aria-labelledby="InvoiceModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="position:absolute; right:5px;z-index:2;">
                <span aria-hidden="true">&times;</span>
            </button>
            <div class="modal-body">
                <h3 class="text-center page-title">Sales Process System</h3>
                <p class="text-center subtitle">Gulshan 1,Navana Tower (7th floor) 45, <br />Gulshan South C/A,Circle 1,<br />Dhaka, Bangladesh</p>
                <div class="row">
                    <div class="col-md-6">
                        <p class="text-left" style="font-size:12px;"><strong>Date: </strong><b id="today"></b></p>
                    </div>
                    <div class="col-md-6">
                        <p class="text-right" style="font-size:12px;"><b id="PaymentStatus" class="order-status-lbl"></b></p>
                    </div>
                </div>
                <h5 class="text-center page-title">Order Summary</h5>
                <hr />
                <h5 class="text-center subtitle"><strong>Products</strong></h5>
                <div class="table-responsive">
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr>
                                <th style="width:5%;">Sl.</th>
                                <th>Name</th>
                                <th style="width:20%;" class="text-center">Quantity</th>
                                <th style="width:20%;" class="text-center">Price</th>
                            </tr>
                        </thead>
                        <tbody id="invoiceOrderScreenProducts"></tbody>
                    </table>
                </div>
                <br />
                <h5 class="text-center subtitle"><strong>Buyers</strong></h5>
                <div class="table-responsive">
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr>
                                <th style="width:5%;">Sl.</th>
                                <th>Name</th>
                                <th style="width:20%;" class="text-center">Payable PCT(%)</th>
                                <th style="width:20%;" class="text-center">Amount</th>
                                <th style="width:20%;" class="text-center">Due</th>
                            </tr>
                        </thead>
                        <tbody id="invoiceOrderScreenBuyers"></tbody>
                    </table>
                </div>
                <div class="nb">
                    <strong style="font-size:12px;">** Vat and taxes are included</strong>
                </div>
            </div>
        </div>
    </div>
</div>

Sales Process/SalesProcess.WEB/Views/Product/Products.cshtml
@{
    ViewBag.Title = "Products";
}
<script type="text/javascript" src="@Url.Content("~/Scripts/App/products.js")"></script>

<div class="card-material">
    <div class="buyers-head row">
        <div class="col-sm-4 col-md-4">
            <h5 class="page-title">Products</h5>
        </div>
        <div class="col-sm-8 col-md-8 text-right">
            <button type="button"
                    class="btn btn-outline-info custom-grid-btn"
                    data-toggle="modal"
                    data-target="#ProductsModal"
                    onclick="AddProductModal(event)">
                <i class="fas fa-plus-circle"></i> Create New Product
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-cyan">
                <tr>
                    <th class="cell-min">Product Name</th>
                    <th class="cell-min text-center">Product Code</th>
                    <th class="cell-min text-center">Product Unit</th>
                    <th class="cell-min text-center">Product Price</th>
                    <th class="cell-min text-center">Stock Quantity</th>
                    <th class="text-center cell-min">Action</th>
                </tr>
            </thead>
            <tbody class="products-list"></tbody>
        </table>
    </div>
</div>
@Html.Partial("_ProductModalWindow")

Sales Process/SalesProcess.WEB/Views/Product/_ProductModalWindow.cshtml
@* Modal Screen *@
<div class="modal fade" id="ProductsModal" tabindex="-1" role="dialog" aria-labelledby="ProductsModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ProductsModalTitle">New Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="ProductsId" />
                    <div class="form-group row">
                        <label for="productName" class="col-sm-4 col-form-label">Name</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="ProductName" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="productCode" class="col-sm-4 col-form-label">Code</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="ProductCode" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="productUnit" class="col-sm-4 col-form-label">Unit</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="ProductUnit" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="productPrice" class="col-sm-4 col-form-label">Price</label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control" id="ProductPrice" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="stockQuantity" class="col-sm-4 col-form-label">Stock Quantity</label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control" id="StockQuantity" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success" id="AddProduct" onclick="AddProduct(event)">Save</button>
                <button type="button" class="btn btn-primary" id="UpdateProduct" onclick="EditProduct(event)">Update</button>
            </div>
        </div>
    </div>
</div>

Sales Process/SalesProcess.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Sales Process</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/bootstrap-select")
    @Scripts.Render("~/bundles/toaster")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/application")
</head>
<body>
    @Html.Partial("_Navigation")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>

Sales Process/SalesProcess.WEB/Views/Shared/_Navigation.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
    <div class="container">
        @Html.ActionLink("Sales Process", "Order", "Order", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavDropdown" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    @Html.ActionLink("Orders", "Order", "Order", null, new { @class = "nav-link active", @rel = "Orders" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Products", "Products", "Product", null, new { @class = "nav-link", @rel = "Products" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Buyers", "BuyersList", "Buyer", null, new { @class = "nav-link", @rel = "Buyers" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Payment", "Payment", "Order", null, new { @class = "nav-link", @rel = "Payment" })
                </li>
            </ul>
        </div>
    </div>
</nav>

<script type="text/javascript">
    $(document).ready(function () {
        var bar = '@ViewBag.Title';
        bar = bar === 'Place Order' ? 'Orders' : bar;
        NavbarActive(bar);
    });
</script>